name: Test API Spec v2beta
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build API Spec v2beta"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch'  
      || github.event.workflow_run.conclusion == 'success'
    env:
      AGENT_REV: "temp"
      GHB_TKN: ${{ secrets.GHB_TKN }}
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
      - name: Test API Spec
        id: test-spec
        run: |
          docker run --e GHB_TKN=${GHB_TKN} ghcr.io/okaneda/api:v2-b
