name: Build API Spec v1
on:
  push:
    branches: [ main ]
    paths:
      - 'api/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
      - name: Build Spec
        #if: github.event_name == 'push'
        id: build-spec
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login https://ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ghcr.io/okaneda/api --build-arg GITHUB_TOKEN="$DOCKER_PASSWORD" .
          docker push ghcr.io/okaneda/api
