name: Build App Spec v2beta
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      #AGENT_REV: "1.2-b.0.reiwa"
      AGENT_REV: "temp"
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
      - name: Build Spec
        id: build-spec
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          tree .
          echo "$DOCKER_PASSWORD" | docker login https://ghcr.io -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ghcr.io/okaneda/app:v2-b --build-arg GITHUB_TOKEN="$DOCKER_PASSWORD" ./app
          docker push ghcr.io/okaneda/app:v2-b
