name: Test OA2 v2-b
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build App Spec v2-b"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch'  
      || github.event.workflow_run.conclusion == 'success'
    env:
      GHB_TKN: ${{ secrets.GHB_TKN }}
    steps:
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
      - name: Test API
        id: test-api
        run: |
          docker run -e GHB_TKN=${GHB_TKN} -e APP_MOD=oa2 ghcr.io/okaneda/app:v2-b
